theme = "tokyonight_transparent"

[editor]
cursor-shape.normal   = "block"
cursor-shape.insert   = "bar"
cursor-shape.select   = "underline"

[[languages]]
name = "nix"
auto-format = true

[languages.formatter]
command = "/nix/store/0j6c8z9x5w7g6v0y8r9k1b2a3c4d5e6f-nixfmt/bin/nixfmt"

[themes.tokyonight_transparent]
inherits = "tokyonight"
ui.background = {}
